<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ValveSurgery extends Model
{
    protected $table = 'valve_surgeries';
    protected $primaryKey = 'caseval_id';
    public $timestamps = true;
    protected $fillable = [
        'valve_pro',
        'explant_position',
        'explant_type',
        'explant_etiology',
        'explant_device',
        'exp_model',
        'exp_uid',
        'second_valve',
        'secexp_pos',
        'secexplant_type',
        'secexplant_etiology',
        'secexplant_devic',
        'secexp_model',
        'secexp_uid',
        'aortic_valve_pro',
        'perform',
        'aortic_performed',
        'transcat',
        'approach',
        'commissural',
        'ringannul',
        'leafletplic',
        'leafletresec',
        'leafletfree',
        'leafletpericard',
        'leafletcomm',
        'leafletdebridt',
        'leafletraphe',
        'repairleak',
        'annular',
        'aorticimp_modelno',
        'aortic_implnt',
        'aorticimp_size',
        'aorticimp_udi',
        'aortic_exp',
        'mitrlvalve',
        'mitral_performed',
        'mitral_perform',
        'repairannol',
        'resection',
        'resecttype',
        'resectloc',
        'leafletplicat',
        'leafletdebrid',
        'fold_plasty',
        'slid_plasty',
        'annular_decal',
        'neochords',
        'neochard',
        'chordal_leaflet_transfer',
        'leaflet_extension',
        'edge_to_edge_repair',
        'mitral_leaflet_clip',
        'mitral_commissurotomy',
        'mitral_commissuroplasty',
        'mitral_cleft_repair',
        'other_repair',
        'attempt_prior',
        'mitral_chords',
        'transcather_replace',
        'mitral_implnt',
        'mi_type',
        'mitral_imn',
        'mitral_size',
        'mitral_udi',
        'mitral_exp',
        'tricuspid',
        'tricuspidper',
        'tricuspid_pro',
        'typeofannulo',
        'transtricusp_replace',
        'tricuspidimplnt',
        'tricuspid_modelno',
        'tricuspid_implnt',
        'tricuspidimp_size',
        'tricuspidimp_udi',
        'tricuspid_exp',
        'pulmonic',
        'pulmonicper',
        'pulmonic_pro',
        'pulmonictrans_replace',
        'pulomnicimplnt',
        'pulmonicimp_modelno',
        'pulmonic_implnt',
        'pulmonicimp_size',
        'pulmonicimp_udi',
        'pulmonic_exp',
    ];
}
